name: 'job_analytics'
version: '1.0.0'
config-version: 2

profile: 'job_analytics' # This must match the name in your profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  job_analytics:
    silver:
      +materialized: table
    gold:
      +materialized: view
